version: '2'
services: 
  nginx: 
    image: nginx 
    ports: 
     - "80:80"
     - "443:443"
    volumes: 
     - ./nginx/html/:/usr/share/nginx/html/
     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/log/:/var/log/nginx/
     - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
     - web
  web:
    image: tomcat
    ports: 
     - "8078:8080"
    volumes:
      - ./tomcat/webapps/:/usr/local/tomcat/webapps/ 
      - ./tomcat/logs/:/usr/local/tomcat/logs/
      - /etc/localtime:/etc/localtime
    depends_on:
     - mysql
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: mysql:5.7
    volumes:  
      - ./db/mysql/data:/var/lib/mysql 
      - ./db/mysql/example_db:/var/example_db 
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime      
    environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_USER: 'root'
           MYSQL_PASS: 'admin'
    ports: 
     - "3307:3306"
