version: '2'
services: 
   redis: 
      image: redis
      container_name: redis
      restart: always
      ports: 
        - 6379:6379
      volumes: 
        - "${REDIS_DIR}/conf:/usr/local/etc/redis"
        - "${REDIS_DIR}/data:/data"
      command: 
        redis-server
      environment:
        - REDIS_PASSWORD=redis#kedacom#123
